#!/usr/bin/python3

from core import exit, lock, profiles

if lock.acquire():
    p = profiles.Profiles('profiles.yml')
    p.next()
    lock.release()
else:
    exit("Another process seems to be running!")
